# Generated by Django 5.2.8 on 2026-06-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('value_type', models.CharField(choices=[('int', '整数'), ('float', '浮点数'), ('str', '字符串'), ('bool', '布尔值'), ('json', 'JSON')], default='str', max_length=16, verbose_name='值类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('category', models.CharField(default='general', max_length=64, verbose_name='分类')),
                ('display_name', models.CharField(blank=True, default='', max_length=128, verbose_name='显示名称')),
                ('editable', models.BooleanField(default=True, verbose_name='允许前端修改')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '全局配置',
                'verbose_name_plural': '全局配置',
                'db_table': 'system_config',
                'ordering': ['category', 'key'],
            },
        ),
    ]
