# Generated by Django 5.2.8 on 2026-06-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0002_seed_default_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='is_secret',
            field=models.BooleanField(default=False, verbose_name='敏感字段'),
        ),
    ]
