# Generated by Django 5.2.15 on 2026-06-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mongodb', 'MongoDB')], default='mysql', max_length=20, verbose_name='数据库类型')),
                ('host', models.CharField(max_length=255, verbose_name='主机地址')),
                ('port', models.PositiveIntegerField(default=3306, verbose_name='端口')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.TextField(verbose_name='密码 (加密存储)')),
                ('environment', models.CharField(choices=[('prod', 'Production'), ('staging', 'Staging'), ('dev', 'Development')], default='prod', max_length=32, verbose_name='环境')),
                ('cluster', models.CharField(blank=True, default='', max_length=128, verbose_name='集群')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用采集')),
                ('collect_interval', models.PositiveIntegerField(default=60, verbose_name='采集间隔 (秒)')),
                ('last_collected_at', models.DateTimeField(blank=True, null=True, verbose_name='上次采集时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据库实例',
                'verbose_name_plural': '数据库实例',
                'db_table': 'collector_database_instance',
                'ordering': ['-created_at'],
            },
        ),
    ]
