# Generated by Django 5.2.15 on 2026-06-11 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(choices=[('scheduled', '定时'), ('manual', '手动')], default='scheduled', max_length=16, verbose_name='触发方式')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], default='success', max_length=16, verbose_name='状态')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时 (ms)')),
                ('queries_collected', models.IntegerField(default=0, verbose_name='采集查询数')),
                ('rows_written', models.IntegerField(default=0, verbose_name='写入行数')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_histories', to='collector.databaseinstance', verbose_name='实例')),
            ],
            options={
                'verbose_name': '采集历史',
                'verbose_name_plural': '采集历史',
                'db_table': 'collector_collection_history',
                'ordering': ['-started_at'],
            },
        ),
    ]
