# Generated by Django 5.2.15 on 2026-06-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_add_collection_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseinstance',
            name='connection_status',
            field=models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected')], default='disconnected', max_length=16, verbose_name='连接状态'),
        ),
        migrations.AddField(
            model_name='databaseinstance',
            name='db_version',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='数据库版本'),
        ),
    ]
