# Generated by Django 5.2.15 on 2026-06-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_add_connection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseinstance',
            name='last_error',
            field=models.TextField(blank=True, default='', verbose_name='最近错误'),
        ),
    ]
