# Generated by Django 5.2.8 on 2026-06-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_add_last_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseinstance',
            name='cluster_role',
            field=models.CharField(choices=[('primary', 'Primary'), ('replica', 'Replica'), ('shard', 'Shard'), ('standalone', 'Standalone')], default='standalone', max_length=20, verbose_name='集群角色'),
        ),
    ]
