# Generated by Django 5.2.15 on 2026-06-12 01:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collector', '0002_add_collection_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('slow_query_time', '慢查询耗时'), ('no_index_ratio', '无索引比例'), ('query_count', '查询总量'), ('custom_sql', '自定义 SQL')], max_length=32, verbose_name='规则类型')),
                ('threshold', models.FloatField(verbose_name='阈值')),
                ('period', models.PositiveIntegerField(default=5, verbose_name='统计周期 (分钟)')),
                ('severity', models.CharField(choices=[('warning', '警告'), ('critical', '严重')], default='warning', max_length=16, verbose_name='严重级别')),
                ('webhook_url', models.CharField(blank=True, max_length=512, verbose_name='Webhook URL')),
                ('custom_sql', models.TextField(blank=True, help_text='返回单个数值与阈值比较。可用占位符: %(service)s %(seconds)s', verbose_name='自定义 SQL')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(blank=True, help_text='留空则对所有活跃实例生效', null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.databaseinstance', verbose_name='绑定实例')),
            ],
            options={
                'verbose_name': '告警规则',
                'verbose_name_plural': '告警规则',
                'db_table': 'alert_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_value', models.FloatField(verbose_name='触发指标值')),
                ('threshold', models.FloatField(verbose_name='触发时阈值')),
                ('status', models.CharField(choices=[('firing', '告警中'), ('resolved', '已恢复')], default='firing', max_length=16, verbose_name='状态')),
                ('fired_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='触发时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='恢复时间')),
                ('notified', models.BooleanField(default=False, verbose_name='已通知')),
                ('notify_error', models.TextField(blank=True, verbose_name='通知错误')),
                ('instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.databaseinstance', verbose_name='实例')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alerts.alertrule')),
            ],
            options={
                'verbose_name': '告警事件',
                'verbose_name_plural': '告警事件',
                'db_table': 'alert_event',
                'ordering': ['-fired_at'],
                'indexes': [models.Index(fields=['rule', 'instance', 'status'], name='alert_event_rule_id_d14341_idx'), models.Index(fields=['status', 'fired_at'], name='alert_event_status_2f5d24_idx')],
            },
        ),
    ]
